export default [
  {
    id: 1,
    state: 'Karnataka',
    area: 'Udupi',
    temperature: '31ºc',
    status: 'Mostly Sunny',
    desc: 'sunny',
    title: 'city1',
    //icon: iconPaths.smallSunnyIcon,
  },
  {
    id: 2,
    state: 'Karnataka',
    area: 'Mangaluru',
    temperature: '29ºc',
    status: 'Rain',
    desc: 'rainy',
    title: 'city2',
    //icon: iconPaths.smallRainIcon,
  },
  {
    id: 3,
    state: 'Maharashtra',
    area: 'Mumbai',
    temperature: '32ºc',
    status: 'Mostly Cloudy',
    desc: 'cloudy',
    title: 'city3',
    // icon: iconPaths.smallCloudIcon,
  },
  {
    id: 4,
    state: 'West Bengal',
    area: 'Kolkatta',
    temperature: '30ºc',
    status: 'Partly Cloudy',
    desc: 'partCloudy',
    title: 'city4',
    // icon: iconPaths.smallPartlyCloudIcon,
  },
  {
    id: 5,
    state: 'Goa',
    area: 'Panaji',
    temperature: '31ºc',
    status: 'Thunderstorm',
    desc: 'thunderstorm',
    title: 'city5',
    // icon: iconPaths.smallThunderIcon,
  },
  {
    id: 6,
    state: 'United States',
    area: 'Newyork',
    temperature: '24ºc',
    status: 'Clear Night',
    desc: 'night',
    title: 'city6',
    // icon: iconPaths.smallNightIcon,
  },
  {
    id: 7,
    state: 'United States',
    area: 'California',
    temperature: '24ºc',
    status: 'Clear Night',
    desc: 'night',
    title: 'city6',
    // icon: iconPaths.smallNightIcon,
  },
];
